// Curated opportunity data for VoltScout.
//
// SEED_OPPORTUNITIES ships with the database on first run so the catalog is
// immediately useful. DISCOVERY_POOL backs the scouting agent's simulated
// mode (used automatically whenever GEMINI_API_KEY is not configured) — it
// represents the "live web" the agent draws newly-indexed roles from, so a
// manual or scheduled scan still has real, citable postings to surface.

export type SeedOpportunity = {
  title: string;
  organization: string;
  orgType: "industry" | "corporate" | "research_institute" | "university";
  domain: string;
  location: string;
  region: "north_america" | "europe" | "asia_pacific" | "global_remote";
  season: "summer_2026" | "fall_2026" | "spring_2027" | "summer_2027" | "year_round";
  level: "undergraduate" | "masters" | "phd";
  deadline: string | null;
  stipendEstimate: string | null;
  housingSupport: string | null;
  visaSupport: boolean;
  description: string;
  responsibilities: string[];
  qualifications: string[];
  techStack: string[];
  sourceUrl: string;
};

export const SEED_OPPORTUNITIES: SeedOpportunity[] = [
  {
    title: "Technical Student Programme — FPGA & Trigger Electronics",
    organization: "CERN",
    orgType: "research_institute",
    domain: "VLSI & Chip Design",
    location: "Geneva, Switzerland",
    region: "europe",
    season: "summer_2026",
    level: "masters",
    deadline: "2026-01-15",
    stipendEstimate: "CHF 4,200 / month",
    housingSupport: "On-site hostel subsidy available",
    visaSupport: true,
    description:
      "Join the CERN EP-ESE group to design and verify FPGA-based trigger and readout electronics for the next-generation LHC detector upgrades. Work alongside physicists and firmware engineers in an international, tier-1 research environment.",
    responsibilities: [
      "Develop VHDL/Verilog modules for high-speed detector readout FPGAs",
      "Simulate and verify timing closure for radiation-tolerant ASICs",
      "Support integration testing of trigger electronics on the accelerator test bench",
      "Document firmware architecture for the collaboration wiki",
    ],
    qualifications: [
      "Enrolled in a Master's or PhD program in Electrical/Computer Engineering or Physics",
      "Coursework in digital logic design, VHDL or Verilog",
      "Familiarity with Xilinx or Intel FPGA toolchains",
      "Strong analytical and lab documentation skills",
    ],
    techStack: ["Xilinx Vivado", "VHDL", "Verilog", "LTspice", "Python"],
    sourceUrl: "https://careers.cern/students",
  },
  {
    title: "Nanoelectronics & Chip Design R&D Intern",
    organization: "IMEC",
    orgType: "research_institute",
    domain: "VLSI & Chip Design",
    location: "Leuven, Belgium",
    region: "europe",
    season: "fall_2026",
    level: "phd",
    deadline: "2026-03-01",
    stipendEstimate: "€2,800 / month",
    housingSupport: "Relocation package for international students",
    visaSupport: true,
    description:
      "Contribute to imec's advanced CMOS scaling research, working on sub-3nm device characterization and custom analog/mixed-signal IP blocks for next-generation compute and sensing chips.",
    responsibilities: [
      "Design and lay out analog/mixed-signal blocks in Cadence Virtuoso",
      "Run SPICE-level simulations for device characterization",
      "Collaborate with process engineers on DFM (design for manufacturability)",
      "Present findings at imec's quarterly research symposium",
    ],
    qualifications: [
      "PhD candidate or final-year Master's in Microelectronics/EE",
      "Hands-on experience with Cadence Virtuoso or Synopsys custom design tools",
      "Understanding of semiconductor device physics",
      "Prior tapeout experience is a strong plus",
    ],
    techStack: ["Cadence Virtuoso", "Synopsys", "MATLAB/Simulink", "Python"],
    sourceUrl: "https://www.imec-int.com/en/careers",
  },
  {
    title: "Hardware Engineering Intern — Custom Silicon",
    organization: "Apple",
    orgType: "corporate",
    domain: "VLSI & Chip Design",
    location: "Cupertino, CA, USA",
    region: "north_america",
    season: "summer_2026",
    level: "undergraduate",
    deadline: "2026-02-01",
    stipendEstimate: "$9,500 / month",
    housingSupport: "Housing stipend included",
    visaSupport: true,
    description:
      "Work within Apple's Silicon Engineering Group to help validate and characterize custom SoC blocks that ship in hundreds of millions of devices, from power management units to camera ISPs.",
    responsibilities: [
      "Build automated test benches for pre-silicon block validation",
      "Debug signal integrity and power delivery issues on bring-up boards",
      "Partner with design and DV teams on coverage closure",
      "Present a capstone project to the hardware org at the end of the internship",
    ],
    qualifications: [
      "Pursuing a BS/MS in Electrical/Computer Engineering",
      "Coursework in digital design, computer architecture, or VLSI",
      "Scripting experience (Python, Perl, or Tcl)",
      "Exposure to lab instrumentation (oscilloscopes, logic analyzers)",
    ],
    techStack: ["Cadence Virtuoso", "Synopsys", "Python", "SystemVerilog"],
    sourceUrl: "https://jobs.apple.com/en-us/search?team=hardware",
  },
  {
    title: "Mixed-Signal IC Design Co-op",
    organization: "Analog Devices",
    orgType: "industry",
    domain: "VLSI & Chip Design",
    location: "Wilmington, MA, USA",
    region: "north_america",
    season: "spring_2027",
    level: "masters",
    deadline: "2026-09-30",
    stipendEstimate: "$8,200 / month",
    housingSupport: null,
    visaSupport: true,
    description:
      "Rotate through ADI's Precision Signal Chain group designing high-resolution data converters and amplifiers used in industrial and instrumentation markets.",
    responsibilities: [
      "Design and simulate mixed-signal building blocks (ADCs, references, amplifiers)",
      "Support silicon bring-up and bench characterization",
      "Develop test scripts for automated characterization benches",
      "Document design trade-offs for the senior design review board",
    ],
    qualifications: [
      "MS in Electrical Engineering with an analog/mixed-signal focus",
      "Proficiency in Cadence Virtuoso and SPICE simulation",
      "Solid grasp of noise, matching, and layout parasitics",
      "Strong written communication for design reviews",
    ],
    techStack: ["Cadence Virtuoso", "LTspice", "MATLAB/Simulink"],
    sourceUrl: "https://www.analog.com/en/about-adi/careers.html",
  },
  {
    title: "Energy Storage & Megapack Power Electronics Intern",
    organization: "Tesla Energy",
    orgType: "corporate",
    domain: "Power Systems & Energy",
    location: "Fremont, CA, USA",
    region: "north_america",
    season: "summer_2026",
    level: "undergraduate",
    deadline: "2026-01-31",
    stipendEstimate: "$8,800 / month",
    housingSupport: "Relocation assistance available",
    visaSupport: true,
    description:
      "Support the Megapack power electronics team designing high-power inverters and battery management interfaces for grid-scale energy storage deployments.",
    responsibilities: [
      "Assist in designing and testing high-power DC/DC and DC/AC converter stages",
      "Run thermal and electrical simulations for power module reliability",
      "Support hardware bring-up and safety validation on the test floor",
      "Analyze field telemetry to identify power electronics failure modes",
    ],
    qualifications: [
      "Junior/Senior in Electrical Engineering with a power electronics focus",
      "Coursework in power conversion, magnetics, or control systems",
      "Experience with PSCAD, PLECS, or MATLAB/Simulink power models",
      "Hands-on lab or project experience with power converters",
    ],
    techStack: ["PSCAD", "MATLAB/Simulink", "Altium Designer", "LTspice"],
    sourceUrl: "https://www.tesla.com/careers/search/?query=power%20electronics%20intern",
  },
  {
    title: "Smart Grid & Grid Automation Intern",
    organization: "Hitachi Energy",
    orgType: "industry",
    domain: "Power Systems & Energy",
    location: "Raleigh, NC, USA",
    region: "north_america",
    season: "summer_2026",
    level: "undergraduate",
    deadline: "2026-02-15",
    stipendEstimate: "$6,800 / month",
    housingSupport: null,
    visaSupport: true,
    description:
      "Join Hitachi Energy's Grid Automation division to help develop protection relays and substation automation software that keeps modern smart grids resilient and efficient.",
    responsibilities: [
      "Support design and testing of protective relaying algorithms",
      "Model distribution grid scenarios in PSCAD/ETAP",
      "Assist with IEC 61850 communication protocol validation",
      "Collaborate with field engineers on substation commissioning data",
    ],
    qualifications: [
      "Pursuing a degree in Electrical Engineering (Power Systems track)",
      "Familiarity with power system protection fundamentals",
      "Exposure to PSCAD, ETAP, or similar grid simulation tools",
      "Interest in renewable integration and grid modernization",
    ],
    techStack: ["PSCAD", "MATLAB/Simulink", "Python"],
    sourceUrl: "https://www.hitachienergy.com/careers",
  },
  {
    title: "Power Electronics R&D Intern — Grid Modernization",
    organization: "Oak Ridge National Laboratory (ORNL)",
    orgType: "research_institute",
    domain: "Power Systems & Energy",
    location: "Oak Ridge, TN, USA",
    region: "north_america",
    season: "summer_2026",
    level: "phd",
    deadline: "2026-01-20",
    stipendEstimate: "$7,600 / month",
    housingSupport: "Housing per diem provided",
    visaSupport: false,
    description:
      "Work in ORNL's Power Electronics and Electric Machinery Research Center on wide-bandgap semiconductor converters for grid modernization and electric transportation research.",
    responsibilities: [
      "Design SiC/GaN-based converter prototypes for EV charging research",
      "Characterize switching losses and thermal performance on the test bench",
      "Contribute to publications on wide-bandgap device reliability",
      "Support DOE program reporting and technical documentation",
    ],
    qualifications: [
      "PhD student in Electrical Engineering (power electronics or energy systems)",
      "Strong foundation in power converter topologies and magnetics design",
      "Experience with PSCAD, PLECS, or MATLAB/Simulink",
      "US citizenship or permanent residency required for lab access",
    ],
    techStack: ["MATLAB/Simulink", "PSCAD", "LTspice"],
    sourceUrl: "https://www.ornl.gov/careers",
    // visaSupport left false intentionally — many DOE national lab
    // programs are restricted to US persons for facility clearance.
  },
  {
    title: "Embedded Firmware Engineering Intern",
    organization: "Arm",
    orgType: "industry",
    domain: "Embedded Systems & IoT",
    location: "Cambridge, UK",
    region: "europe",
    season: "summer_2026",
    level: "undergraduate",
    deadline: "2026-02-10",
    stipendEstimate: "£3,100 / month",
    housingSupport: null,
    visaSupport: true,
    description:
      "Build and optimize low-level firmware for Arm Cortex-M based IoT reference platforms, working closely with the CPU architecture and software ecosystem teams.",
    responsibilities: [
      "Develop and debug RTOS-based firmware for Cortex-M reference boards",
      "Optimize interrupt latency and power consumption for IoT use cases",
      "Contribute test cases to Arm's open-source firmware SDKs",
      "Write technical notes for the developer ecosystem",
    ],
    qualifications: [
      "Pursuing a degree in Electrical/Computer Engineering or CS with an embedded focus",
      "Proficiency in C/C++ and familiarity with FreeRTOS or Zephyr",
      "Understanding of microcontroller peripherals (SPI, I2C, UART, DMA)",
      "Comfortable with JTAG/SWD debugging tools",
    ],
    techStack: ["FreeRTOS", "MATLAB/Simulink", "KiCad"],
    sourceUrl: "https://careers.arm.com/students-graduates",
  },
  {
    title: "Automotive Embedded Systems Intern",
    organization: "Bosch",
    orgType: "corporate",
    domain: "Automotive & Hardware",
    location: "Stuttgart, Germany",
    region: "europe",
    season: "fall_2026",
    level: "undergraduate",
    deadline: "2026-04-01",
    stipendEstimate: "€2,400 / month",
    housingSupport: "Subsidized housing near campus",
    visaSupport: true,
    description:
      "Support Bosch's ADAS hardware team developing embedded control units for advanced driver-assistance systems, from sensor fusion boards to functional-safety validation.",
    responsibilities: [
      "Assist with schematic capture and PCB layout for ECU prototypes",
      "Develop diagnostic firmware for CAN/LIN-based automotive networks",
      "Support HIL (hardware-in-the-loop) test rig setup",
      "Document ISO 26262 functional safety test evidence",
    ],
    qualifications: [
      "Enrolled in Electrical/Automotive Engineering program",
      "Coursework in embedded systems and automotive networking (CAN/LIN)",
      "Experience with Altium Designer or similar PCB design tools",
      "German or English proficiency for cross-team collaboration",
    ],
    techStack: ["Altium Designer", "FreeRTOS", "MATLAB/Simulink"],
    sourceUrl: "https://www.bosch.com/careers/students/",
  },
  {
    title: "RF & 5G Systems Engineering Intern",
    organization: "Qualcomm",
    orgType: "industry",
    domain: "RF & 5G/6G Telecom",
    location: "San Diego, CA, USA",
    region: "north_america",
    season: "summer_2026",
    level: "masters",
    deadline: "2026-02-20",
    stipendEstimate: "$9,000 / month",
    housingSupport: "Housing stipend included",
    visaSupport: true,
    description:
      "Join Qualcomm's Modem Systems group researching RF front-end architectures and link-level algorithms for next-generation 5G/6G mobile platforms.",
    responsibilities: [
      "Model RF front-end performance trade-offs in MATLAB/Simulink",
      "Support lab characterization of transceiver prototypes",
      "Analyze link budgets for mmWave and sub-6GHz bands",
      "Collaborate with standards teams on 3GPP contribution drafts",
    ],
    qualifications: [
      "MS candidate in Electrical Engineering with an RF/communications focus",
      "Strong grasp of RF circuit fundamentals and link budget analysis",
      "MATLAB proficiency; Python a plus",
      "Coursework in digital communications or antenna theory",
    ],
    techStack: ["MATLAB/Simulink", "LTspice", "Python"],
    sourceUrl: "https://www.qualcomm.com/company/careers/students-and-new-grads",
  },
  {
    title: "Quantum Hardware & Photonics Research Fellow",
    organization: "MIT Lincoln Laboratory",
    orgType: "research_institute",
    domain: "Photonics & Quantum Hardware",
    location: "Lexington, MA, USA",
    region: "north_america",
    season: "year_round",
    level: "phd",
    deadline: "2026-03-15",
    stipendEstimate: "$7,200 / month",
    housingSupport: null,
    visaSupport: false,
    description:
      "Contribute to superconducting qubit control electronics and cryogenic photonic interconnect research within the Quantum Information Science group.",
    responsibilities: [
      "Design cryo-compatible control electronics for qubit readout chains",
      "Support photonic packaging and alignment for quantum interconnects",
      "Analyze noise sources in low-temperature RF signal chains",
      "Co-author technical reports and conference submissions",
    ],
    qualifications: [
      "PhD student in EE, Applied Physics, or related field",
      "Background in RF/microwave engineering or photonics",
      "Experience with cryogenic or low-noise measurement systems",
      "US citizenship required for laboratory security clearance",
    ],
    techStack: ["MATLAB/Simulink", "LTspice", "Python"],
    sourceUrl: "https://www.ll.mit.edu/careers",
  },
  {
    title: "Biomedical Sensor Systems Intern",
    organization: "Medtronic",
    orgType: "corporate",
    domain: "Biomedical & Sensors",
    location: "Minneapolis, MN, USA",
    region: "north_america",
    season: "summer_2026",
    level: "undergraduate",
    deadline: "2026-02-05",
    stipendEstimate: "$6,500 / month",
    housingSupport: null,
    visaSupport: true,
    description:
      "Support the design of low-power analog front-ends for implantable and wearable biomedical sensing devices within Medtronic's Restorative Therapies Group.",
    responsibilities: [
      "Prototype low-noise analog front-end circuits for biosignal acquisition",
      "Support bench validation of sensor accuracy and power consumption",
      "Assist with regulatory documentation for design verification",
      "Collaborate with firmware engineers on embedded signal processing",
    ],
    qualifications: [
      "Pursuing a BS in Electrical or Biomedical Engineering",
      "Coursework in analog circuit design and signal processing",
      "Familiarity with low-power embedded systems",
      "Interest in medical device design controls (ISO 13485 a plus)",
    ],
    techStack: ["LTspice", "Altium Designer", "MATLAB/Simulink", "FreeRTOS"],
    sourceUrl: "https://careers.medtronic.com/",
  },
  {
    title: "Robotics & Motion Controls Intern",
    organization: "Boston Dynamics",
    orgType: "industry",
    domain: "Robotics & Controls",
    location: "Waltham, MA, USA",
    region: "north_america",
    season: "summer_2026",
    level: "masters",
    deadline: "2026-02-12",
    stipendEstimate: "$8,600 / month",
    housingSupport: "Relocation support available",
    visaSupport: true,
    description:
      "Work with the Electrical Systems team designing motor controller electronics and real-time control firmware for next-generation legged robots.",
    responsibilities: [
      "Design and validate motor driver and sensing PCBs",
      "Tune closed-loop torque/position control algorithms",
      "Support real-time embedded firmware development for actuator nodes",
      "Debug electromechanical integration issues during field testing",
    ],
    qualifications: [
      "MS candidate in Electrical/Mechatronics Engineering",
      "Experience with motor control theory (FOC, PID tuning)",
      "Proficiency with embedded C/C++ and real-time operating systems",
      "PCB design experience (Altium Designer or KiCad)",
    ],
    techStack: ["Altium Designer", "FreeRTOS", "MATLAB/Simulink", "KiCad"],
    sourceUrl: "https://bostondynamics.com/careers/",
  },
  {
    title: "Digital IC Design Fellowship",
    organization: "Stanford SystemX Alliance",
    orgType: "university",
    domain: "VLSI & Chip Design",
    location: "Stanford, CA, USA",
    region: "north_america",
    season: "year_round",
    level: "phd",
    deadline: "2026-05-01",
    stipendEstimate: "$5,400 / month",
    housingSupport: "Graduate housing priority",
    visaSupport: true,
    description:
      "A university-industry fellowship pairing PhD researchers with SystemX member companies to advance digital IC design methodologies for next-generation compute systems.",
    responsibilities: [
      "Research RTL design and verification methodologies for large SoCs",
      "Publish findings in peer-reviewed EDA/VLSI conferences",
      "Mentor undergraduate researchers on digital design labs",
      "Present quarterly progress to industry sponsor companies",
    ],
    qualifications: [
      "PhD student in Electrical Engineering or Computer Science (VLSI focus)",
      "Strong RTL design skills in Verilog/SystemVerilog",
      "Experience with Synopsys or Cadence digital design flows",
      "Publication record or strong research potential",
    ],
    techStack: ["Synopsys", "Cadence Virtuoso", "Xilinx Vivado"],
    sourceUrl: "https://systemx.stanford.edu/",
  },
  {
    title: "Power Electronics Research Intern — EV Fast Charging",
    organization: "National Renewable Energy Laboratory (NREL)",
    orgType: "research_institute",
    domain: "Power Systems & Energy",
    location: "Golden, CO, USA",
    region: "north_america",
    season: "summer_2026",
    level: "masters",
    deadline: "2026-01-25",
    stipendEstimate: "$6,900 / month",
    housingSupport: "Housing per diem provided",
    visaSupport: true,
    description:
      "Support NREL's Power Electronics and Electric Machines group researching high-efficiency DC fast-charging converter topologies for electric vehicle infrastructure.",
    responsibilities: [
      "Model converter topologies for extreme fast-charging applications",
      "Support hardware-in-the-loop testing of charger prototypes",
      "Analyze thermal and efficiency data from lab test campaigns",
      "Contribute to technical reports for DOE Vehicle Technologies Office",
    ],
    qualifications: [
      "MS student in Electrical Engineering (power electronics focus)",
      "Experience with PLECS, PSCAD, or MATLAB/Simulink power modeling",
      "Understanding of wide-bandgap semiconductor devices",
      "Strong data analysis and technical writing skills",
    ],
    techStack: ["MATLAB/Simulink", "PSCAD", "LTspice"],
    sourceUrl: "https://www.nrel.gov/careers/",
  },
];

// Summer 2027 cycle — postings for the next application cycle out, with
// deadlines still ahead of the current date so they show up as open in the
// catalog once seeded.
export const SUMMER_2027_OPPORTUNITIES: SeedOpportunity[] = [
  {
    title: "Custom Silicon Validation Intern",
    organization: "Intel",
    orgType: "corporate",
    domain: "VLSI & Chip Design",
    location: "Hillsboro, OR, USA",
    region: "north_america",
    season: "summer_2027",
    level: "undergraduate",
    deadline: "2027-01-15",
    stipendEstimate: "$8,400 / month",
    housingSupport: "Housing stipend included",
    visaSupport: true,
    description:
      "Join Intel's Client Computing Group to validate next-generation SoC blocks ahead of production, working across pre-silicon emulation and post-silicon bring-up.",
    responsibilities: [
      "Build automated validation test benches for SoC IP blocks",
      "Debug signal integrity and timing issues on bring-up boards",
      "Support coverage closure with the design verification team",
    ],
    qualifications: [
      "Pursuing a BS/MS in Electrical/Computer Engineering",
      "Coursework in digital design or computer architecture",
      "Scripting experience (Python or Perl)",
    ],
    techStack: ["Xilinx Vivado", "Python", "SystemVerilog"],
    sourceUrl: "https://jobs.intel.com/en/students",
  },
  {
    title: "Grid Power Electronics Intern",
    organization: "Siemens Energy",
    orgType: "industry",
    domain: "Power Systems & Energy",
    location: "Erlangen, Germany",
    region: "europe",
    season: "summer_2027",
    level: "masters",
    deadline: "2026-12-01",
    stipendEstimate: "€2,600 / month",
    housingSupport: "Relocation assistance available",
    visaSupport: true,
    description:
      "Support Siemens Energy's Grid Technologies division designing high-voltage converter systems for renewable integration and HVDC transmission projects.",
    responsibilities: [
      "Model converter topologies for HVDC transmission applications",
      "Support grid-code compliance simulations",
      "Analyze field performance data from pilot installations",
    ],
    qualifications: [
      "MS student in Electrical Engineering (power systems focus)",
      "Experience with PSCAD or MATLAB/Simulink power modeling",
      "Interest in renewable grid integration",
    ],
    techStack: ["PSCAD", "MATLAB/Simulink"],
    sourceUrl: "https://jobs.siemens-energy.com/students",
  },
  {
    title: "Memory Systems Design Intern",
    organization: "Samsung Semiconductor",
    orgType: "corporate",
    domain: "VLSI & Chip Design",
    location: "Hwaseong, South Korea",
    region: "asia_pacific",
    season: "summer_2027",
    level: "undergraduate",
    deadline: "2027-02-01",
    stipendEstimate: "₩4,200,000 / month",
    housingSupport: "On-site housing provided",
    visaSupport: true,
    description:
      "Support Samsung's Memory Division on next-generation DRAM and NAND circuit design, working alongside process and product engineering teams.",
    responsibilities: [
      "Design and simulate memory array peripheral circuits",
      "Support characterization of memory cell reliability",
      "Document design trade-offs for the review board",
    ],
    qualifications: [
      "Pursuing a BS/MS in Electrical Engineering",
      "Coursework in digital or mixed-signal IC design",
      "Familiarity with Cadence or Synopsys tools",
    ],
    techStack: ["Cadence Virtuoso", "Synopsys"],
    sourceUrl: "https://www.samsungsemiconductor.com/careers/students",
  },
  {
    title: "Autonomous Driving Embedded Systems Intern",
    organization: "Waymo",
    orgType: "industry",
    domain: "Embedded Systems & IoT",
    location: "Mountain View, CA, USA",
    region: "north_america",
    season: "summer_2027",
    level: "masters",
    deadline: "2027-01-20",
    stipendEstimate: "$9,300 / month",
    housingSupport: "Housing stipend included",
    visaSupport: true,
    description:
      "Develop embedded firmware and hardware-in-the-loop test infrastructure for Waymo's autonomous vehicle compute and sensor platforms.",
    responsibilities: [
      "Develop real-time embedded firmware for sensor interface boards",
      "Build hardware-in-the-loop test rigs for compute platforms",
      "Debug firmware issues using JTAG/logic analyzers",
    ],
    qualifications: [
      "MS student in Electrical/Computer Engineering",
      "Strong C/C++ and RTOS experience",
      "Understanding of real-time sensor interfacing",
    ],
    techStack: ["FreeRTOS", "Python"],
    sourceUrl: "https://waymo.com/careers/",
  },
  {
    title: "RF Front-End Research Intern",
    organization: "Ericsson",
    orgType: "industry",
    domain: "RF & 5G/6G Telecom",
    location: "Remote (Global)",
    region: "global_remote",
    season: "summer_2027",
    level: "phd",
    deadline: "2027-02-15",
    stipendEstimate: "$7,800 / month",
    housingSupport: null,
    visaSupport: true,
    description:
      "Research RF front-end architectures and link-level algorithms for next-generation 6G radio platforms within Ericsson Research's global remote research track.",
    responsibilities: [
      "Model RF front-end trade-offs in MATLAB/Simulink",
      "Analyze link budgets for sub-6GHz and mmWave bands",
      "Contribute to standards-track technical reports",
    ],
    qualifications: [
      "PhD student in EE with an RF/communications focus",
      "Strong MATLAB proficiency",
      "Coursework in digital communications or antenna theory",
    ],
    techStack: ["MATLAB/Simulink", "Python"],
    sourceUrl: "https://www.ericsson.com/en/careers/students",
  },
];

export type DiscoveryLead = SeedOpportunity & {
  domain: string;
};

// Additional realistic postings the simulated scouting agent can "discover"
// on a run, organized loosely so targeted dispatch (by discipline) pulls
// relevant leads. In simulated mode a run samples a handful of these that
// aren't already in the catalog and inserts them as newly indexed roles.
export const DISCOVERY_POOL: DiscoveryLead[] = [
  {
    title: "Analog IC Design Intern — Power Management",
    organization: "Texas Instruments",
    orgType: "industry",
    domain: "VLSI & Chip Design",
    location: "Dallas, TX, USA",
    region: "north_america",
    season: "summer_2026",
    level: "undergraduate",
    deadline: "2026-02-28",
    stipendEstimate: "$7,800 / month",
    housingSupport: null,
    visaSupport: true,
    description:
      "Design and characterize analog building blocks for next-generation power management ICs used across industrial and automotive markets.",
    responsibilities: [
      "Design analog sub-blocks (bandgaps, regulators) in Cadence Virtuoso",
      "Run corner and Monte Carlo simulations for process variation",
      "Support silicon bring-up in the characterization lab",
    ],
    qualifications: [
      "Pursuing a BS/MS in Electrical Engineering",
      "Coursework in analog IC design",
      "Cadence or SPICE simulation experience",
    ],
    techStack: ["Cadence Virtuoso", "LTspice"],
    sourceUrl: "https://careers.ti.com/students/",
  },
  {
    title: "FPGA Design Intern — Autonomous Systems",
    organization: "NVIDIA",
    orgType: "industry",
    domain: "Embedded Systems & IoT",
    location: "Santa Clara, CA, USA",
    region: "north_america",
    season: "summer_2026",
    level: "masters",
    deadline: "2026-02-18",
    stipendEstimate: "$9,800 / month",
    housingSupport: "Housing stipend included",
    visaSupport: true,
    description:
      "Develop FPGA-based prototyping platforms for validating next-generation SoC IP blocks ahead of tapeout.",
    responsibilities: [
      "Write and verify RTL for FPGA emulation platforms",
      "Debug timing closure and resource utilization issues",
      "Automate regression test infrastructure",
    ],
    qualifications: [
      "MS student in Electrical/Computer Engineering",
      "Verilog/SystemVerilog and Xilinx Vivado experience",
      "Scripting proficiency (Python/Tcl)",
    ],
    techStack: ["Xilinx Vivado", "FreeRTOS"],
    sourceUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite",
  },
  {
    title: "Grid-Scale Battery Storage Controls Intern",
    organization: "Fluence Energy",
    orgType: "industry",
    domain: "Power Systems & Energy",
    location: "Arlington, VA, USA",
    region: "north_america",
    season: "summer_2026",
    level: "undergraduate",
    deadline: "2026-03-05",
    stipendEstimate: "$6,200 / month",
    housingSupport: null,
    visaSupport: true,
    description:
      "Support controls engineering for utility-scale battery energy storage systems, from state-of-charge algorithms to grid-code compliance testing.",
    responsibilities: [
      "Model battery management and inverter control algorithms",
      "Support grid-code compliance simulations (PSCAD/PSSE)",
      "Analyze field performance data from deployed storage sites",
    ],
    qualifications: [
      "Junior/Senior in Electrical Engineering (power systems focus)",
      "MATLAB/Simulink or PSCAD experience",
      "Interest in renewable energy integration",
    ],
    techStack: ["PSCAD", "MATLAB/Simulink"],
    sourceUrl: "https://fluenceenergy.com/careers/",
  },
  {
    title: "6G Wireless Research Intern",
    organization: "Nokia Bell Labs",
    orgType: "research_institute",
    domain: "RF & 5G/6G Telecom",
    location: "Murray Hill, NJ, USA",
    region: "north_america",
    season: "summer_2026",
    level: "phd",
    deadline: "2026-02-01",
    stipendEstimate: "$7,400 / month",
    housingSupport: null,
    visaSupport: true,
    description:
      "Research physical-layer algorithms and RF architectures for 6G radio access networks within Bell Labs' Wireless Research group.",
    responsibilities: [
      "Prototype PHY-layer algorithms in MATLAB and validate on test benches",
      "Characterize RF front-end performance at sub-THz frequencies",
      "Co-author papers for IEEE conferences",
    ],
    qualifications: [
      "PhD student in EE/Telecom with a wireless communications focus",
      "Strong MATLAB and signal processing background",
      "Publication record preferred",
    ],
    techStack: ["MATLAB/Simulink", "Python"],
    sourceUrl: "https://www.bell-labs.com/careers/",
  },
  {
    title: "Silicon Photonics Packaging Intern",
    organization: "Ayar Labs",
    orgType: "industry",
    domain: "Photonics & Quantum Hardware",
    location: "Santa Clara, CA, USA",
    region: "north_america",
    season: "summer_2026",
    level: "masters",
    deadline: "2026-03-01",
    stipendEstimate: "$8,000 / month",
    housingSupport: null,
    visaSupport: true,
    description:
      "Support optical packaging and test development for silicon photonics chiplets used in next-generation datacenter interconnects.",
    responsibilities: [
      "Support fiber-to-chip alignment and packaging test development",
      "Characterize optical link performance across temperature corners",
      "Document packaging process yield data",
    ],
    qualifications: [
      "MS student in EE, Applied Physics, or Photonics",
      "Lab experience with optical alignment/characterization",
      "Familiarity with photonic simulation tools",
    ],
    techStack: ["MATLAB/Simulink", "LTspice"],
    sourceUrl: "https://ayarlabs.com/careers/",
  },
  {
    title: "Implantable Devices Electronics Intern",
    organization: "Boston Scientific",
    orgType: "corporate",
    domain: "Biomedical & Sensors",
    location: "St. Paul, MN, USA",
    region: "north_america",
    season: "summer_2026",
    level: "undergraduate",
    deadline: "2026-02-08",
    stipendEstimate: "$6,300 / month",
    housingSupport: null,
    visaSupport: true,
    description:
      "Support ultra-low-power circuit design for next-generation implantable neuromodulation devices.",
    responsibilities: [
      "Prototype low-power analog/digital circuit blocks",
      "Support bench and bio-compatibility test protocols",
      "Assist with design history file documentation",
    ],
    qualifications: [
      "Pursuing a BS in Electrical or Biomedical Engineering",
      "Analog circuit design coursework",
      "Attention to regulatory documentation detail",
    ],
    techStack: ["LTspice", "Altium Designer"],
    sourceUrl: "https://www.bostonscientific.com/en-US/careers.html",
  },
  {
    title: "Electric Powertrain Controls Intern",
    organization: "Rivian",
    orgType: "corporate",
    domain: "Automotive & Hardware",
    location: "Irvine, CA, USA",
    region: "north_america",
    season: "summer_2026",
    level: "undergraduate",
    deadline: "2026-02-14",
    stipendEstimate: "$7,200 / month",
    housingSupport: "Relocation stipend available",
    visaSupport: true,
    description:
      "Support development of motor control firmware and inverter validation for Rivian's electric powertrain systems.",
    responsibilities: [
      "Support motor control algorithm tuning on dyno test benches",
      "Validate inverter firmware against safety requirements",
      "Analyze vehicle telemetry for powertrain performance",
    ],
    qualifications: [
      "Junior/Senior in Electrical Engineering",
      "Coursework in power electronics or controls",
      "Embedded C experience",
    ],
    techStack: ["MATLAB/Simulink", "FreeRTOS", "Altium Designer"],
    sourceUrl: "https://rivian.com/careers",
  },
  {
    title: "Humanoid Robotics Perception Electronics Intern",
    organization: "Figure AI",
    orgType: "industry",
    domain: "Robotics & Controls",
    location: "Sunnyvale, CA, USA",
    region: "north_america",
    season: "summer_2026",
    level: "masters",
    deadline: "2026-02-22",
    stipendEstimate: "$9,200 / month",
    housingSupport: "Housing stipend included",
    visaSupport: true,
    description:
      "Design sensor interface electronics and real-time signal processing pipelines for humanoid robot perception systems.",
    responsibilities: [
      "Design sensor interconnect PCBs for vision/IMU modules",
      "Optimize real-time signal processing pipelines",
      "Support electromechanical integration on robot prototypes",
    ],
    qualifications: [
      "MS student in Electrical/Robotics Engineering",
      "PCB design and embedded systems experience",
      "Interest in humanoid robotics hardware",
    ],
    techStack: ["Altium Designer", "FreeRTOS", "KiCad"],
    sourceUrl: "https://www.figure.ai/careers",
  },
  {
    title: "Data Center Power Delivery Intern",
    organization: "Google",
    orgType: "corporate",
    domain: "Power Systems & Energy",
    location: "Mountain View, CA, USA",
    region: "north_america",
    season: "summer_2026",
    level: "masters",
    deadline: "2026-02-04",
    stipendEstimate: "$9,600 / month",
    housingSupport: "Housing stipend included",
    visaSupport: true,
    description:
      "Support power delivery architecture design for hyperscale data center infrastructure, from rack-level converters to facility power distribution.",
    responsibilities: [
      "Model power delivery efficiency for rack-scale converters",
      "Support hardware validation of power distribution units",
      "Analyze reliability data from deployed data center fleets",
    ],
    qualifications: [
      "MS student in Electrical Engineering (power electronics focus)",
      "Experience with power converter design and analysis",
      "Strong data analysis skills (Python/MATLAB)",
    ],
    techStack: ["MATLAB/Simulink", "LTspice", "Python"],
    sourceUrl: "https://careers.google.com/students/",
  },
  {
    title: "Embedded Systems Intern — Satellite Avionics",
    organization: "SpaceX",
    orgType: "industry",
    domain: "Embedded Systems & IoT",
    location: "Hawthorne, CA, USA",
    region: "north_america",
    season: "summer_2026",
    level: "undergraduate",
    deadline: "2026-01-30",
    stipendEstimate: "$9,000 / month",
    housingSupport: null,
    visaSupport: false,
    description:
      "Develop embedded firmware for Starlink satellite avionics systems, working on real-time flight software and hardware-in-the-loop test infrastructure.",
    responsibilities: [
      "Develop real-time embedded firmware for avionics boards",
      "Build hardware-in-the-loop test rigs for satellite subsystems",
      "Debug flight software issues using JTAG/logic analyzers",
    ],
    qualifications: [
      "Pursuing a BS in Electrical/Computer Engineering",
      "Strong C/C++ and RTOS experience",
      "US person status required (ITAR)",
    ],
    techStack: ["FreeRTOS", "Altium Designer"],
    sourceUrl: "https://www.spacex.com/careers/",
    // visaSupport left false — ITAR-controlled avionics roles typically
    // require US person status.
  },
  {
    title: "Digital Design Verification Intern",
    organization: "AMD",
    orgType: "industry",
    domain: "VLSI & Chip Design",
    location: "Austin, TX, USA",
    region: "north_america",
    season: "fall_2026",
    level: "masters",
    deadline: "2026-04-15",
    stipendEstimate: "$8,700 / month",
    housingSupport: null,
    visaSupport: true,
    description:
      "Join AMD's GPU verification team building UVM-based testbenches to validate next-generation graphics and compute silicon.",
    responsibilities: [
      "Develop UVM testbenches and coverage models",
      "Debug RTL failures using waveform analysis",
      "Automate regression pipelines for nightly verification runs",
    ],
    qualifications: [
      "MS student in Electrical/Computer Engineering",
      "SystemVerilog/UVM coursework or project experience",
      "Scripting experience (Python, Perl)",
    ],
    techStack: ["Synopsys", "Cadence Virtuoso", "Xilinx Vivado"],
    sourceUrl: "https://careers.amd.com/careers-home/students",
  },
  {
    title: "Wearable Sensor Systems Research Intern",
    organization: "Fraunhofer Institute for Microelectronic Circuits and Systems",
    orgType: "research_institute",
    domain: "Biomedical & Sensors",
    location: "Duisburg, Germany",
    region: "europe",
    season: "fall_2026",
    level: "masters",
    deadline: "2026-05-01",
    stipendEstimate: "€2,100 / month",
    housingSupport: null,
    visaSupport: true,
    description:
      "Research low-power wearable biosensor front-ends and wireless telemetry for continuous health monitoring applications.",
    responsibilities: [
      "Prototype low-power analog front-end circuits for biosensing",
      "Develop wireless telemetry firmware for wearable prototypes",
      "Support clinical pilot data collection and analysis",
    ],
    qualifications: [
      "MS student in Electrical Engineering or Biomedical Engineering",
      "Analog front-end design experience",
      "Familiarity with low-power wireless protocols (BLE)",
    ],
    techStack: ["LTspice", "MATLAB/Simulink", "FreeRTOS"],
    sourceUrl: "https://www.ims.fraunhofer.de/en/Jobs-Career.html",
  },
  {
    title: "Autonomous Vehicle Radar Systems Intern",
    organization: "Zoox",
    orgType: "industry",
    domain: "RF & 5G/6G Telecom",
    location: "Foster City, CA, USA",
    region: "north_america",
    season: "summer_2026",
    level: "masters",
    deadline: "2026-02-25",
    stipendEstimate: "$8,900 / month",
    housingSupport: "Housing stipend included",
    visaSupport: true,
    description:
      "Support design and validation of automotive radar sensor front-ends used in Zoox's autonomous vehicle perception stack.",
    responsibilities: [
      "Support RF front-end design and lab characterization of radar sensors",
      "Analyze radar signal processing performance across drive scenarios",
      "Collaborate with perception software teams on sensor fusion tuning",
    ],
    qualifications: [
      "MS student in EE with RF/radar systems coursework",
      "MATLAB proficiency for signal processing analysis",
      "Understanding of FMCW radar principles",
    ],
    techStack: ["MATLAB/Simulink", "Python"],
    sourceUrl: "https://zoox.com/careers/",
  },
  {
    title: "Renewable Microgrid Controls Fellowship",
    organization: "ETH Zurich Power Systems Laboratory",
    orgType: "university",
    domain: "Power Systems & Energy",
    location: "Zurich, Switzerland",
    region: "europe",
    season: "year_round",
    level: "phd",
    deadline: "2026-04-20",
    stipendEstimate: "CHF 3,600 / month",
    housingSupport: "Graduate housing assistance",
    visaSupport: true,
    description:
      "Research fellowship on distributed control strategies for renewable-heavy microgrids, combining power systems modeling with real-time hardware-in-the-loop validation.",
    responsibilities: [
      "Develop distributed control algorithms for microgrid stability",
      "Validate models on the lab's real-time digital simulator",
      "Publish results in IEEE Transactions on Power Systems",
    ],
    qualifications: [
      "PhD student in Electrical Engineering (power systems focus)",
      "Strong background in control theory and power system dynamics",
      "MATLAB/Simulink or real-time simulation experience",
    ],
    techStack: ["MATLAB/Simulink", "PSCAD"],
    sourceUrl: "https://www.eeh.ee.ethz.ch/psl/careers.html",
  },
  {
    title: "Quantum Control Electronics Intern",
    organization: "IonQ",
    orgType: "industry",
    domain: "Photonics & Quantum Hardware",
    location: "College Park, MD, USA",
    region: "north_america",
    season: "summer_2026",
    level: "phd",
    deadline: "2026-02-16",
    stipendEstimate: "$8,300 / month",
    housingSupport: null,
    visaSupport: true,
    description:
      "Design low-noise RF and laser control electronics for trapped-ion quantum computing systems.",
    responsibilities: [
      "Design low-noise RF control boards for ion trap electrodes",
      "Support laser lock electronics characterization",
      "Debug system-level noise sources affecting qubit fidelity",
    ],
    qualifications: [
      "PhD student in EE or Applied Physics",
      "RF/analog circuit design experience",
      "Familiarity with low-noise measurement techniques",
    ],
    techStack: ["LTspice", "MATLAB/Simulink"],
    sourceUrl: "https://ionq.com/careers",
  },
];
